name: exemplo-deploy

on: [push]
jobs:
  publish-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/mar-celo/exgolem .
          docker push ghcr.io/mar-celo/exgolem
